
INSERT INTO public.cities (name) VALUES
('Adamantina'),('Aguaí'),('Agudos'),('Americana'),('Américo Brasiliense'),
('Amparo'),('Andradina'),('Aparecida'),('Apiaí'),('Araçatuba'),
('Araraquara'),('Araras'),('Artur Nogueira'),('Arujá'),('Assis'),
('Atibaia'),('Avaré'),('Bariri'),('Barra Bonita'),('Barretos'),
('Barueri'),('Bastos'),('Batatais'),('Bauru'),('Bebedouro'),
('Bertioga'),('Birigui'),('Boituva'),('Botucatu'),('Bragança Paulista'),
('Brodowski'),('Brotas'),('Buritama'),('Cabreúva'),('Caçapava'),
('Cachoeira Paulista'),('Caieiras'),('Cajamar'),('Cajuru'),('Campinas'),
('Campo Limpo Paulista'),('Cândido Mota'),('Capão Bonito'),('Capivari'),('Caraguatatuba'),
('Carapicuíba'),('Catanduva'),('Cerquilho'),('Cesário Lange'),('Charqueada'),
('Clementina'),('Colina'),('Conchal'),('Cordeirópolis'),('Cosmópolis'),
('Cotia'),('Cravinhos'),('Cruzeiro'),('Cubatão'),('Descalvado'),
('Diadema'),('Dois Córregos'),('Dracena'),('Echaporã'),('Elias Fausto'),
('Embu das Artes'),('Embu-Guaçu'),('Engenheiro Coelho'),('Espírito Santo do Pinhal'),('Estrela d''Oeste'),
('Fernandópolis'),('Ferraz de Vasconcelos'),('Franca'),('Francisco Morato'),('Franco da Rocha'),
('Garça'),('Guaíra'),('Guapiaçu'),('Guaraci'),('Guaratinguetá'),
('Guariba'),('Guarujá'),('Guarulhos'),('Guzolândia'),('Hortolândia'),
('Ibaté'),('Ibitinga'),('Ibiúna'),('Igarapava'),('Ilhabela'),
('Indaiatuba'),('Iperó'),('Iracemápolis'),('Itatiba'),('Itatinga'),
('Itu'),('Itupeva'),('Ituverava'),('Jaborandi'),('Jaboticabal'),
('Jacareí'),('Jaguariúna'),('Jales'),('Jambeiro'),('Jandira'),
('Jardinópolis'),('Jaú'),('José Bonifácio'),('Jundiaí'),('Junqueirópolis'),
('Juquitiba'),('Laranjal Paulista'),('Leme'),('Lençóis Paulista'),('Limeira'),
('Lins'),('Lorena'),('Louveira'),('Lucélia'),('Macatuba'),
('Mairinque'),('Mairiporã'),('Manduri'),('Marília'),('Martinópolis'),
('Matão'),('Mauá'),('Miguelópolis'),('Mineiros do Tietê'),('Mirandópolis'),
('Mirassol'),('Mococa'),('Mogi das Cruzes'),('Mogi Guaçu'),('Mogi Mirim'),
('Mongaguá'),('Monte Alto'),('Monte Aprazível'),('Monte Azul Paulista'),('Monte Mor'),
('Morro Agudo'),('Morungaba'),('Narandiba'),('Nhandeara'),('Nova Odessa'),
('Novo Horizonte'),('Olímpia'),('Orlândia'),('Osasco'),('Osvaldo Cruz'),
('Ourinhos'),('Palmital'),('Panorama'),('Paraguaçu Paulista'),('Paranapanema'),
('Pariquera-Açu'),('Patrocínio Paulista'),('Paulínia'),('Pederneiras'),('Pedra Bela'),
('Pedregulho'),('Penápolis'),('Pereira Barreto'),('Peruíbe'),('Piedade'),
('Pilar do Sul'),('Pindamonhangaba'),('Pindorama'),('Piracaia'),('Piracicaba'),
('Piraju'),('Pirangi'),('Pirapozinho'),('Pirassununga'),('Piratininga'),
('Poá'),('Pompeia'),('Pontal'),('Porto Feliz'),('Porto Ferreira'),
('Pradópolis'),('Praia Grande'),('Presidente Epitácio'),('Presidente Prudente'),('Presidente Venceslau'),
('Promissão'),('Quatá'),('Rancharia'),('Regente Feijó'),('Registro'),
('Ribeirão Bonito'),('Ribeirão Pires'),('Ribeirão Preto'),('Rincão'),('Rinópolis'),
('Rio Claro'),('Rio das Pedras'),('Rio Grande da Serra'),('Rosana'),('Roseira'),
('Rubiácea'),('Sabino'),('Salto'),('Salto de Pirapora'),('Santa Adélia'),
('Santa Bárbara d''Oeste'),('Santa Cruz da Conceição'),('Santa Cruz das Palmeiras'),('Santa Cruz do Rio Pardo'),('Santa Fé do Sul'),
('Santa Gertrudes'),('Santa Isabel'),('Santa Lúcia'),('Santa Rita do Passa Quatro'),('Santa Rosa de Viterbo'),
('Santana de Parnaíba'),('Santo Anastácio'),('Santo André'),('Santos'),('São Bernardo do Campo'),
('São Caetano do Sul'),('São Carlos'),('São João da Boa Vista'),('São Joaquim da Barra'),('São José do Rio Pardo'),
('São José do Rio Preto'),('São José dos Campos'),('São Manuel'),('São Miguel Arcanjo'),('São Paulo'),
('São Pedro'),('São Roque'),('São Sebastião'),('São Vicente'),('Serrana'),
('Sertãozinho'),('Socorro'),('Sorocaba'),('Sumaré'),('Suzano'),
('Tabapuã'),('Taboão da Serra'),('Taguaí'),('Tambaú'),('Tanabi'),
('Taquaritinga'),('Taquarituba'),('Taquarivaí'),('Tatuí'),('Taubaté'),
('Teodoro Sampaio'),('Terra Roxa'),('Tietê'),('Tremembé'),('Três Fronteiras'),
('Tupã'),('Tupi Paulista'),('Ubatuba'),('Valinhos'),('Valparaíso'),
('Vargem Grande do Sul'),('Várzea Paulista'),('Viradouro'),('Vinhedo'),('Vista Alegre do Alto'),
('Votuporanga'),('Votorantim'),('Águas de Lindóia'),('Águas de São Pedro'),('Álvares Machado'),
('Itanhaém'),('Itapecerica da Serra'),('Itapetininga'),('Itapeva'),('Itapevi'),
('Itapira'),('Itaquaquecetuba'),('Ilha Solteira'),('Igaraçu do Tietê'),('Ipuã'),
('Itajobi'),('Itápolis'),('Jarinu'),('General Salgado'),('Guararapes'),
('Guarantã'),('Guararema'),('Holambra'),('Iacanga'),('Itaberá'),
('Itaju'),('Monte Castelo'),('Neves Paulista'),('Nova Europa'),('Óleo'),
('Ouroeste'),('Palmares Paulista'),('Paraíso'),('Pedreira'),('Piacatu'),
('Populina'),('Potim'),('Presidente Bernardes'),('Riolândia'),('São Lourenço da Serra'),
('Gavião Peixoto'),('Getulina'),('Iepê'),('Lavínia'),('Lucianópolis'),
('Lutécia'),('Maracaí'),('Mendonça'),('Nantes'),('Ocauçu'),
('Oscar Bressane'),('Parapuã'),('Paulistânia'),('Platina'),('Poloni'),
('Queiroz'),('Quintana'),('Reginópolis'),('Sales'),('Santópolis do Aguapeí'),
('Sebastianópolis do Sul'),('Sud Mennucci'),('Ubirajara'),('União Paulista'),('Uru');
